// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogkqourzlitggkpdvvkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9na3FvdXJ6bGl0Z2drcGR2dmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NTI5NDgsImV4cCI6MjA1OTAyODk0OH0.go0RBefrxWAcF1Hex9Wfm-XCnSgjQ7-AEYaQHIAou4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);